name: mockdoor.playground
services:
  - name: mockdoor-server
    project: mockdoor/MockDoor/Server/MockDoor.Server.csproj
    replicas: 1
    env:
    - name: DeploymentConfiguration__PathBase
      value: /dev/mockdoor/
    - name: DeploymentConfiguration__SeedOnStartup
      value: Data/SampleSeedData.json
    bindings:
      - port: 44304
        protocol: https
        routes: [ /dev/mockdoor/ ]         
  - name: shopping-store-ui
    project: BFFUISample/src/Server/Blazor6.Server.csproj
    replicas: 1
    env_file:
      - ./tye-mockdoor-shared.env
    bindings:
      - port: 5006
        protocol: https
  - name: shopping-store-api
    project: BFFUISample/src/StoreApi/StoreApi.csproj
    replicas: 1
    env_file:
      - ./tye-mockdoor-shared.env
    bindings:
      - port: 7125
        protocol: https
  - name: shopping-stock-api
    project: BFFUISample/src/StockApi/StockApi.csproj
    replicas: 1
    env_file:
      - ./tye-mockdoor-shared.env
    bindings:
      - port: 7089
        protocol: https
  - name: shopping-order-processor-api
    project: BFFUISample/src/OrderProcessor/OrderProcessorApi/OrderProcessorApi.csproj
    replicas: 1
    env_file:
      - ./tye-mockdoor-shared.env
    bindings:
      - port: 7054
        protocol: https
  - name: identity-server
    project: IdentityServerSample/src/IdentityServer/IdentityServer.csproj
    replicas: 1
    env:
      - name: Authentication__UserStoreUrl
        value: https://localhost:44304/dev/mockdoor/api/mock/gmt/auth/userstore/demo
      - name: Authentication__StoreDemoUrl
        value: https://localhost:5006
    bindings:
      - port: 5001
        protocol: https
  - name: user-store
    project: IdentityServerSample/src/UserStore/UserStore.csproj
    replicas: 1
    bindings:
      - port: 7274
        protocol: https
  - name: user-permission
    project: IdentityServerSample/src/UserPermissions/UserPermissions/UserPermissions.csproj
    replicas: 1
    bindings:
      - port: 7087
        protocol: https
  - name: data-dash-ui
    project: DataDash/DataDash/DataDash.csproj
    replicas: 1
    env:
      - name: Pages__default
        value: UrlToPoll=https://localhost:44304/dev/mockdoor/api/mock/gmt/monitor/datadashapi/demo/StoreMonitor;IntervalBetweenUpdatesInSeconds=2;HttpAuthHeaderScheme=bearer;HttpAuthHeaderValue=sfghwrewfrgrtt2
      - name: Pages__data
        value: UrlToPoll=https://localhost:44304/dev/mockdoor/api/mock/gmt/monitor/datadashapi/demo/Test;IntervalBetweenUpdatesInSeconds=2;HttpAuthHeaderScheme=bearer;HttpAuthHeaderValue=sfghwrewfrgrtt2w
      - name: Pages__pageName
        value: ms=default,data,data,pageName
    bindings:
      - port: 7094
        protocol: https
  - name: data-dash-api
    project: DataDash/TestWebApi/TestWebApi.csproj
    replicas: 1
    env_file:
      - ./tye-mockdoor-shared.env
    bindings:
      - port: 5013
        protocol: http
